apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: library-app
type: Opaque
data:
  # The password is 'password', base64 encoded.
  # To encode your own: echo -n 'yourpassword' | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=